#!/usr/bin/env bash
# This script mirrors one branch with master

MIRROR="slurm-s3it"
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" == "master" ]; then
  git checkout "$MIRROR"
  git rebase master
  git checkout master
fi
