#!/usr/bin/env bash
# This script mirrors the slurm-s3it branch with master,
# while keeping it ahead by a single commit for sbatch command replacements

MIRROR="slurm-s3it"
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" == "master" ]; then
  printf "%s\n" "Syncing $MIRROR with master"
  git stash
  git checkout "$MIRROR"
  git rebase master
  git push --force origin "$MIRROR"
  git checkout master
  git stash pop
fi
