#!/usr/bin/env bash
# This script sets up a pre-commit hook to keep the development log
# and pythonic dependencies up-to-date

# check for python dependency commands
test_pipreqs=$(command -v pipreqs)
test_poetry=$(command -v poetry)

# check if develop.org has been staged for commit
develop_change=$(git diff --cached --exit-code ./docs/develop.org \
                     > /dev/null; echo $?)

# update requirements.txt given conditions
if [ -f "./poetry.lock" ] && [ -n "$test_poetry" ]; then
  poetry export -f requirements.txt --without-hashes -o requirements.txt
  git add "requirements.txt"
elif [ ! -f "./poetry.lock" ] && [ -n "$test_pipreqs" ]; then
  pipreqs --force .
  git add "requirements.txt"
fi

# update develop.md given conditions
if [ -f ./docs/develop.org ] && [ "$develop_change" -eq "1" ]; then
  # convert todos.org to todos.md
  pandoc -f org -t markdown -o ./docs/develop.md ./docs/develop.org
  # replace TODOs cleanly
  sed -i 's/\[TODO\]{.*}/**TODO**/g' ./docs/develop.md
  sed -i 's/\[DONE\]{.*}/**DONE**/g' ./docs/develop.md
  # add requirements.txt to stage for commit
  git add ./docs/develop.md
fi
