#!/usr/bin/env bash
# This script sets up a pre-commit hook to keep the development log
# and pythonic dependencies up-to-date, as well as format shell scripts

# check for various dependency executables
test_poetry=$(command -v poetry)
test_shfmt=$(command -v shfmt)
test_R_styler=$(
  Rscript -e 'styler::style_file()' &>/dev/null
  echo $?
)

# check if poetry files have been staged for commit
poetry_change=$(
  git diff --cached --exit-code pyproject.toml poetry.lock \
    &>/dev/null
  echo $?
)

# check if develop.org has been staged for commit
develop_change=$(
  git diff --cached --exit-code ./docs/develop.org \
    &>/dev/null
  echo $?
)

# check if R src files have been staged for commit
R_change=$(
  git diff --cached --exit-code ./src/visualize_wmt19_paraphrases_de_en.R \
    &>/dev/null
  echo $?
)

# check which shell scripts have been staged for commit
scripts_change=($(git diff --name-only --cached --diff-filter=d ./scripts/))

# update requirements.txt given conditions
if [ -f "./poetry.lock" ] && [ -n "$test_poetry" ] && [ "$poetry_change" -eq "1" ]; then
  printf "%s\n" "Syncing python dependencies with poetry"
  poetry export -f requirements.txt --without-hashes -o requirements.txt
  git add "requirements.txt"
fi

# update develop.md given conditions
if [ -f ./docs/develop.org ] && [ "$develop_change" -eq "1" ]; then
  printf "%s\n" "Syncing develop.md with develop.org"
  # convert todos.org to todos.md
  pandoc -f org -t markdown -o ./docs/develop.md ./docs/develop.org
  # replace TODOs cleanly
  sed -i 's/\[TODO\]{.*}/**TODO**/g' ./docs/develop.md
  sed -i 's/\[DONE\]{.*}/**DONE**/g' ./docs/develop.md
  # add requirements.txt to stage for commit
  git add ./docs/develop.md
fi

# format staged shell scripts
if [ -n "$test_shfmt" ] && [ "${#scripts_change[@]}" -ne "0" ]; then
  printf "%s\n" "Formatting shell scripts"
  shfmt -w -i 2 "${scripts_change[@]}"
  git add "${scripts_change[@]}"
fi

# format R files
if [ "$test_R_styler" -eq "0" ] && [ "$R_change" -eq "1" ]; then
  printf "%s\n" "Formatting R scripts"
  Rscript -e 'styler::style_file("./src/visualize_wmt19_paraphrases_de_en.R")'
  git add "./src/visualize_wmt19_paraphrases_de_en.R"
fi
